name: di504
channels:
- fastai
- pytorch
- defaults
dependencies:
- numpy
- pandas
- jupyter
- matplotlib
- pillow
- fastcore
- nbdev
- fastprogress
- pytorch
- torchvision
- pip
- pip:
  - torch-summary

