name: di504-term-project
channels:
- fastai
- pytorch
- defaults
dependencies:
- fastcore>=1.3.8
- fastprogress>=0.2.4
- pytorch>=1.7.0
- torchvision>=0.8
- matplotlib
- pandas>=1.0.0
- pillow>=6.0.0
- jupyter

